### ISSUE TITLE
any issues or tricks using multiple sliders on same page ?

### ISSUE THREAD

**Issue by walkoffhomerun** [bqworks/slider-pro#259]
i am using example2 slider.  usually i only do 1 per page but i will need to do multiple sliders on the same page.  any issues or tricks to make this work?  I am assuming each slider will get it's own 
```
<div id="example2" class="slider-pro">
				<div class="sp-slides"> 
```
2 sections of div's ??????

but will each slider operate independently and will the arrow buttons work independently?  or do i have to give each slider it's own name like "example2", example2b" etc?

**Comment by davidghi** [comment]
Hi. There shouldn't be any issues; the slider will work independently. If all the sliders will have the same configuration you could could instantiate them using the class: `$('.slider-pro').sliderPro({})`. If they will have different configuration, you should give each a different ID.

Cheers!

**Comment by walkoffhomerun** [comment]
i have the script live in a preview but only the 1st slider displays and the other 2 do not display.  so i can clarify....this page is autopopulated from a database query.  so the page is preloaded with 1  sliderpro template basically and the the database loop will duplicated the sliderpro multiple times.  I am just going to paste in the source that is shown thru a "view-source:" in a browser.
testing link: https://www.investorconstruction.com/propertysearch/management/bootstraptest-db-alt-sliderpro.asp

But, here is what you will see in the view source thru the browser:

```
<!-- 1st slider pro -->
<div id="example2" class="slider-pro">
	<div class="sp-slides"> 

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/IMG_20150218_161413.jpg" >
		</div>

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/IMG_20150218_163505.jpg" >
		</div>

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/IMG_20150722_115452.jpg" >
		</div>

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/IMG_20150829_122305.jpg" >
		</div>

	</div>
</div>  

<!-- 2nd slider pro -->
<div id="example2" class="slider-pro">
	<div class="sp-slides"> 

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/limestone front.jpg" >
		</div>

	</div>
</div>  

<!-- 3rd slider pro -->
<div id="example2" class="slider-pro">
	<div class="sp-slides"> 

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/IMG_20160127_124556.jpg" >
		</div>

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/IMG_20160127_123925.jpg" >
		</div>

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/IMG_20150829_194920.jpg" >
		</div>

		<div class="sp-slide">
			<img class="sp-image" src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" data-src="https://www.investorconstruction.com/propertysearch/ticketphotos/207/IMG_20150829_122528.jpg" >
		</div>
					
	</div>
</div>  
```

**Comment by walkoffhomerun** [comment]
i just plugged those same 3 example2 sliders into another page, this time a static html page where i replaced a working sliderpro carousel with these 2 sliderpro carousels.  I get the same problem.  the 1st one shows but the 2nd and 3rd ones do NOT show even though their data is visible in the page source thru the browser

**Comment by davidghi** [comment]
ID's should be unique for each slider. If you want to instantiate them at once, you can use a class:

```javascript
$('.slider-pro').sliderPro({
...
})
```

Cheers!

**Comment by walkoffhomerun** [comment]
where would i put this?  my issue with embedding it on the same page is that i am defer loading scripts and js is loaded at the bottom as well as defer loaded so anything i embed on page is processed before the deferred loaded js runs.  Here is my deferred js loaded thru a file:

```
POTENZA.SliderProScrolling = function () {
  if ($('#example2scrolling').exists()) {
    loadScript(plugin_path + 'slider-pro/jquery.sliderPro.min.js', function() {
		$( '#example2scrolling' ).sliderPro({
			height: 90,
			visibleSize: '100%',
			arrows: false,
			buttons: false, /* bottom image buttons for navigation */
			slideDistance: 50,
			slideAnimationDuration: 4000,
			autoSlideSize: true //required for narrower images and not have white gaps on sides of narrower images
		});
		$( '.sp-next-arrow' ).addClass( 'fa-chevron-right' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' ).addClass( 'JP-test' );
		$( '.sp-previous-arrow' ).addClass( 'fa-chevron-left' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' ).addClass( 'JP-test' );	
		$( '#example2scrolling' ).sliderPro('resize'); 
		$(".sp-slide").css({ opacity: 1 }); //overrides the dimmed out opacity for previous and next images that was coded by me into the main slider pro css file
		
		// Part 1 of the continuous slide option. 2nd part is css code added into the main slider pro css file
		setTimeout(function(){
			$( '.slider-pro' ).sliderPro( 'nextSlide' );
		}, 200);

		$( '.slider-pro' ).on( 'gotoSlideComplete', function() {
		$( '.slider-pro' ).sliderPro( 'nextSlide' );
		} ); 
			
     });
   }     
};
```
and then at the bottom of that script page it does this call:

```
//Document ready functions
    $document.ready(function () {

		POTENZA.SliderPro(),

    });
```

**Comment by davidghi** [comment]
To instantiate all the sliders at once, you need to replace `#example2` in the code above with `.slider-pro`:

```javascript
...
loadScript(plugin_path + 'slider-pro/jquery.sliderPro.min.js', function() {
		$( '.slider-pro' ).sliderPro({
			width: 700,
			height: 450,
...
```

Since all the sliders on the page have the `slider-pro` class, the code will instantiate them all. Or, if you want to instantiate them separately, you can give each slider a different ID (`slider1`, `slider2`, `slider3`), and then instantiate the sliders one by one:

```javascript
if ($('.slider-pro').exists()) { // check if there is at least one slider in the page
    loadScript(plugin_path + 'slider-pro/jquery.sliderPro.min.js', function() {
        if ($('#slider1').exists()) {
		$( '#slider1' ).sliderPro({
			width: 700,
			height: 450,
                        ...
		});
        }

        if ($('#slider2').exists()) {
		$( '#slider2' ).sliderPro({
			width: 700,
			height: 450,
                        ...
		});
        }

        if ($('#slider3').exists()) {
		$( '#slider3' ).sliderPro({
			width: 700,
			height: 450,
                        ...
		});
        }

	$( '.sp-next-arrow' ).addClass( 'fa-chevron-right' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' );
	$( '.sp-previous-arrow' ).addClass( 'fa-chevron-left' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' );	
	$( '.slider-pro' ).sliderPro('resize'); 
     });
}
```
This is an approximation. I'm not sure if I understood your code correctly, but in my examples you can see what I mean by instantiating them at once or one by one.

Cheers!

**Comment by walkoffhomerun** [comment]
after some playing around with it i got it to work with the top first option you gave.  However, you mentioned only changing `#example2` over to `.slider-pro` in the javascript config area but you also have to change the same in the actual page <div>.  I assumed you had to do that but for someone else reading this they might not realize that.

however, there is an issue if you are DEFER loading your sliderpro javascript config file like i am.  if you choose to load your sliderpro javascript config files on the page in the <head> section then that <head> section config settings will get overwritten by the lazy load config settings.  basic stuff but i had to mess around with this and add a separate config section in the defer loaded javascript config file to get all this to work.  so now i have 2 separate sliderpro config sections:

for my normal #example2 sliderpro sliders i have this:
```
if ($('#example2').exists()) {
    loadScript(plugin_path + 'slider-pro/jquery.sliderPro.min.js', function() {
		$( '#example2' ).sliderPro({
			width: 700,
			height: 450,
                        .... more line items
```

then for my pages that have multiple #example2 sliders on the same page where i had to change the `#example2` over to `.slider-pro` then i have this section:
```
if ($('.slider-pro').exists()) {
    loadScript(plugin_path + 'slider-pro/jquery.sliderPro.min.js', function() {
		$( '.slider-pro' ).sliderPro({
			width: 700,
			height: 450,
                        .... more line items
```

david showed this in his example above

**Comment by walkoffhomerun** [comment]
David, after making these changes i am noticing error messages in browser Console -> error message screens.  Here is what the error message is:

```
jQuery.Deferred exception: $(...).sliderPro is not a function TypeError: $(...).sliderPro is not a function
    at https://www.investorconstruction.com/js/custom.js:918:22
    at loadScript (https://www.investorconstruction.com/js/custom.js:1000:7)
    at Object.POTENZA.MultipleSliderPro (https://www.investorconstruction.com/js/custom.js:917:5)
    at HTMLDocument.<anonymous> (https://www.investorconstruction.com/js/custom.js:1047:11)
    at l (https://www.investorconstruction.com/js/jquery-3.3.1.min.js:2:29375)
    at c (https://www.investorconstruction.com/js/jquery-3.3.1.min.js:2:29677) undefined
```

it is talking that it is not a function.  i simply copied the other slider pro section and renamed the function. i had 2 slider pro functions already and now there is 3 and all 3 have different names.  here is that section which is in the js/custom.js file

```
POTENZA.SliderPro = function () {
  if ($('#example2').exists()) {
    loadScript(plugin_path + 'slider-pro/jquery.sliderPro.min.js', function() {
		$( '#example2' ).sliderPro({
			width: 700,
			height: 450,
			aspectRatio: 1.5,
			visibleSize: '100%',
			arrows: true,
			buttons: false, /* bottom image buttons for navigation */
			slideDistance: 5,
			fullScreen: true, 
			autoSlideSize: true //required for narrower images and not have white gaps on sides of narrower images
		});
		$( '.sp-next-arrow' ).addClass( 'fa-chevron-right' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' );
		$( '.sp-previous-arrow' ).addClass( 'fa-chevron-left' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' );	
		$( '#example2' ).sliderPro('resize'); 
     });
   }     
};

 /********* this one is SPECIFICALLY for multiple sliders on the SAME PAGE with the same div name.  
 Had to replace #example2 with .slider-pro in BOTH THIS CONFIG FILE AS WELL AS THE ON PAGE <div> container according to developer
************/
POTENZA.MultipleSliderPro = function () {
  if ($('.slider-pro').exists()) {
    loadScript(plugin_path + 'slider-pro/jquery.sliderPro.min.js', function() {
		$( '.slider-pro' ).sliderPro({
			width: 700,
			height: 450,
			aspectRatio: 1.5,
			visibleSize: '100%',
			autoplay: false,
			arrows: true,
			buttons: false, /* bottom image buttons for navigation */
			slideDistance: 5,
			fullScreen: true, 
			autoSlideSize: true //required for narrower images and not have white gaps on sides of narrower images
		});
		$( '.sp-next-arrow' ).addClass( 'fa-chevron-right' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' );
		$( '.sp-previous-arrow' ).addClass( 'fa-chevron-left' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' );	
		$( '.slider-pro' ).sliderPro('resize'); 
     });
   }     
};

POTENZA.SliderProScrolling = function () {
  if ($('#example2scrolling').exists()) {
    loadScript(plugin_path + 'slider-pro/jquery.sliderPro.min.js', function() {
		$( '#example2scrolling' ).sliderPro({
			height: 90,
			visibleSize: '100%',
			arrows: false,
			buttons: false, /* bottom image buttons for navigation */
			slideDistance: 50,
			slideAnimationDuration: 4000,
			autoSlideSize: true //required for narrower images and not have white gaps on sides of narrower images
		});
		$( '.sp-next-arrow' ).addClass( 'fa-chevron-right' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' ).addClass( 'JP-test' );
		$( '.sp-previous-arrow' ).addClass( 'fa-chevron-left' ).addClass( 'icon' ).addClass( 'icon-white' ).addClass( 'icon-sm' ).addClass( 'JP-test' );	
		$( '#example2scrolling' ).sliderPro('resize'); 
		$(".sp-slide").css({ opacity: 1 }); //overrides the dimmed out opacity for previous and next images that was coded by me into the main slider pro css file
		
		// Part 1 of the continuous slide option. 2nd part is css code added into the main slider pro css file
		setTimeout(function(){
			$( '.slider-pro' ).sliderPro( 'nextSlide' );
		}, 200);

		$( '.slider-pro' ).on( 'gotoSlideComplete', function() {
		$( '.slider-pro' ).sliderPro( 'nextSlide' );
		} ); 
			
     });
   }     
};
```
and then they are called at the bottom of that same page

```
 //Document ready functions
    $document.ready(function () {
        POTENZA.megaMenu(),
        POTENZA.counters(),
        POTENZA.accordion(),
        POTENZA.carousel(),
        POTENZA.mailchimp(),
        POTENZA.contactform(),
        POTENZA.countdownTimer(),
        POTENZA.goToTop(),
        POTENZA.mediav(),
        POTENZA.googlemapopen(),
        POTENZA.mobileslider(),
        POTENZA.onepagenav(),
        POTENZA.mediaPopups(),
        POTENZA.pniceScroll(),        
        POTENZA.datetimepick(),
        POTENZA.datatables(),
        POTENZA.wowanimation(),
        POTENZA.googlemaps(),
        POTENZA.fancyselect(),
        POTENZA.searchbox(),
        POTENZA.cartbox(),
        POTENZA.raindrops(),
        POTENZA.sidepanel(),
        POTENZA.slickslider(),
		POTENZA.slicksliderscrolling(),
        POTENZA.typer(),
        POTENZA.stickyFooter(),
        POTENZA.masonry(),
		POTENZA.SliderPro(),
		POTENZA.MultipleSliderPro(),
		POTENZA.SliderProScrolling(),
        POTENZA.mobileview();
    });
```

**Comment by walkoffhomerun** [comment]
david, checking to see if you saw this

**Comment by davidghi** [comment]
Hi,

You don't need both the code for `POTENZA.SliderPro` because `POTENZA.MultipleSliderPro` is sufficient. All the sliders have the `slider-pro` class, including the single slider with the `example2` ID, so the code from `POTENZA.MultipleSliderPro` will instantiate `example2` as well.

You would need different instantiations only if the configuration of the sliders were different, but in this case they are the same.

Cheers!
